document.addEventListener('DOMContentLoaded', () => {
  const stateKey = 'rkEventState';
  const state = JSON.parse(localStorage.getItem(stateKey) || '{}');
  const saveState = patch => { Object.assign(state, patch); localStorage.setItem(stateKey, JSON.stringify(state)); };
  const refreshIcons = () => window.lucide?.createIcons();
  const closeModals = () => { document.querySelectorAll('.modal-backdrop.open').forEach(modal => { modal.classList.remove('open'); modal.setAttribute('aria-hidden', 'true'); }); document.body.style.overflow = ''; };
  const openModal = id => { const modal = document.getElementById(id); if (!modal) return; closeModals(); modal.classList.add('open'); modal.setAttribute('aria-hidden', 'false'); document.body.style.overflow = 'hidden'; refreshIcons(); };
  const showToast = message => { const toast = document.querySelector('.toast'); toast.textContent = message; toast.classList.add('show'); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove('show'), 2400); };
  refreshIcons();
  const faSocialIcons = { Instagram: 'instagram', Facebook: 'facebook', Twitter: 'twitter', Email: 'envelope' };
  document.querySelectorAll('.footer-social a[aria-label]').forEach(link => { const icon = link.querySelector('i'); const iconName = faSocialIcons[link.getAttribute('aria-label')]; if (icon && iconName) { icon.className = `fa fa-${iconName}`; icon.removeAttribute('data-lucide'); } });
  document.querySelectorAll('[data-modal]').forEach(button => button.addEventListener('click', () => openModal(button.dataset.modal)));
  document.querySelectorAll('.modal-close').forEach(button => button.addEventListener('click', closeModals));
  document.querySelectorAll('.modal-backdrop').forEach(backdrop => backdrop.addEventListener('click', event => { if (event.target === backdrop) closeModals(); }));
  document.addEventListener('keydown', event => { if (event.key === 'Escape') { closeModals(); document.getElementById('mobileNav')?.classList.remove('open'); } });
  document.querySelectorAll('[data-scroll]').forEach(button => button.addEventListener('click', () => document.getElementById(button.dataset.scroll)?.scrollIntoView({ behavior: 'smooth' })));
  document.querySelectorAll('.event-option').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('.event-option').forEach(item => item.classList.remove('selected')); button.classList.add('selected'); saveState({ eventType: button.dataset.event }); showToast(`${button.dataset.event} mode selected`); }));
  const briefInner = document.querySelector('.brief-inner');
  if (briefInner && !briefInner.querySelector('.brief-services')) {
    const quickServices = document.createElement('div'); quickServices.className = 'brief-services'; quickServices.innerHTML = '<span class="brief-services-label">Also bring us in for</span><button data-service="Bridal & groom entries"><i data-lucide="sparkles"></i> Entries</button><button data-service="Decoration & sound setup"><i data-lucide="audio-lines"></i> Decor + sound</button><button data-service="International artist shows"><i data-lucide="mic-2"></i> Artist shows</button><button data-service="Full event organisation"><i data-lucide="layers-3"></i> Full coordination</button>';
    briefInner.appendChild(quickServices); quickServices.querySelectorAll('button').forEach(button => button.addEventListener('click', () => { saveState({ service: button.dataset.service }); showToast(`${button.dataset.service} added to your event brief`); openModal('briefModal'); })); refreshIcons();
  }
  const makerImage = document.getElementById('makerModalImage'); const makerTitle = document.getElementById('makerTitle'); const makerMeta = document.getElementById('makerMeta'); const makerRating = document.getElementById('makerRating'); const makerBriefButton = document.getElementById('makerBriefButton'); let activeMaker = null;
  const makerGrid = document.querySelector('.maker-grid');
  if (makerGrid && !makerGrid.querySelector('[data-name="Pulse Production Co."]')) {
    const extraMakers = [{ name: 'Pulse Production Co.', category: 'production', meta: 'Production · Delhi', rating: '4.9', photo: 'maker-photo-four' }, { name: 'Afterglow Artists', category: 'artist', meta: 'Artist shows · Mumbai', rating: '4.8', photo: 'maker-photo-five' }, { name: 'The Event Desk', category: 'coordination', meta: 'Coordination · Gurgaon', rating: '5.0', photo: 'maker-photo-six' }];
    extraMakers.forEach(maker => { const card = document.createElement('button'); card.className = 'maker-card'; card.dataset.category = maker.category; card.dataset.name = maker.name; card.innerHTML = `<div class="maker-photo ${maker.photo}"><span class="online-tag"><i data-lucide="circle"></i> Available</span><span class="save-maker"><i data-lucide="heart"></i></span></div><div class="maker-details"><div><h4>${maker.name}</h4><p>${maker.meta}</p></div><span class="maker-rating">${maker.rating} <i data-lucide="star"></i></span></div>`; makerGrid.appendChild(card); });
    const filterTabs = document.querySelector('.filter-tabs'); ['production|Production', 'artist|Artist shows', 'coordination|Coordination'].forEach(item => { const [filter, label] = item.split('|'); const button = document.createElement('button'); button.className = 'filter-tab'; button.dataset.filter = filter; button.textContent = label; filterTabs.appendChild(button); button.addEventListener('click', () => { document.querySelectorAll('.filter-tab').forEach(tab => tab.classList.remove('active')); button.classList.add('active'); filterMakers(); }); }); refreshIcons();
  }
  document.querySelectorAll('.maker-card').forEach(card => card.addEventListener('click', () => { activeMaker = card; makerTitle.textContent = card.dataset.name; makerMeta.textContent = card.querySelector('p').textContent; makerRating.textContent = card.querySelector('.maker-rating').textContent.trim().split(' ')[0]; makerImage.className = `maker-modal-image ${card.querySelector('.maker-photo').className.split(' ').find(name => name.startsWith('maker-photo-'))}`; openModal('makerModal'); }));
  makerBriefButton?.addEventListener('click', () => { saveState({ maker: activeMaker?.dataset.name || '' }); closeModals(); showToast(`${activeMaker?.dataset.name || 'Maker'} added to your event brief`); openModal('briefModal'); });
  document.querySelectorAll('.service-card').forEach(card => card.addEventListener('click', () => { saveState({ service: card.dataset.service }); showToast(`${card.dataset.service} added to your event brief`); openModal('briefModal'); }));
  document.querySelectorAll('.capability-card').forEach(card => card.addEventListener('click', () => { saveState({ service: card.dataset.service }); showToast(`${card.dataset.service} added to your event brief`); openModal('briefModal'); }));
  document.querySelectorAll('.step').forEach(step => step.addEventListener('click', () => { document.querySelectorAll('.step').forEach(item => item.classList.remove('active')); step.classList.add('active'); showToast(step.querySelector('strong').textContent); }));
  document.querySelectorAll('.filter-tab').forEach(tab => tab.addEventListener('click', () => { document.querySelectorAll('.filter-tab').forEach(item => item.classList.remove('active')); tab.classList.add('active'); filterMakers(); })); document.getElementById('makerSearch')?.addEventListener('input', filterMakers);
  function filterMakers() { const category = document.querySelector('.filter-tab.active')?.dataset.filter || 'all'; const query = (document.getElementById('makerSearch')?.value || '').toLowerCase(); document.querySelectorAll('.maker-card').forEach(card => { const match = (category === 'all' || card.dataset.category === category) && `${card.dataset.name} ${card.dataset.category}`.toLowerCase().includes(query); card.classList.toggle('is-hidden', !match); }); }
  const range = document.getElementById('budgetRange'); const budgetValue = document.getElementById('budgetValue'); const budgetText = document.getElementById('budgetText');
  range?.addEventListener('input', () => { const value = Number(range.value); budgetValue.textContent = `₹ ${new Intl.NumberFormat('en-IN').format(value)}`; budgetText.textContent = value < 400000 ? 'An intimate celebration with the essentials, beautifully considered.' : value < 800000 ? 'A beautiful, focused celebration with room for the details that matter.' : 'A full creative production with space for a few unforgettable surprises.'; saveState({ budget: value }); }); if (state.budget && range) { range.value = state.budget; range.dispatchEvent(new Event('input')); }
  const stories = [{ quote: 'RK understood the feeling before we had the words for it. The whole wedding felt like <em>us</em> — just more alive.', name: 'Meera & Kunal', meta: 'Wedding, Jaipur · 2025', avatar: 'M' }, { quote: 'We stopped juggling vendors and started enjoying the countdown. That change was everything.', name: 'Aanya & Rohan', meta: 'Sangeet, Delhi · 2026', avatar: 'A' }, { quote: 'Our launch had the energy of a big idea and the calm of a team that had already thought of everything.', name: 'Mosaic Labs', meta: 'Brand event, Gurgaon · 2025', avatar: 'M' }]; let storyIndex = 0;
  function renderStory() { const story = stories[storyIndex]; document.getElementById('storyQuote').innerHTML = story.quote; document.getElementById('storyName').textContent = story.name; document.getElementById('storyMeta').textContent = story.meta; document.getElementById('storyAvatar').textContent = story.avatar; document.getElementById('storyCount').innerHTML = `0${storyIndex + 1} <i></i> 03`; }
  document.getElementById('storyNext')?.addEventListener('click', () => { storyIndex = (storyIndex + 1) % stories.length; renderStory(); }); document.getElementById('storyPrev')?.addEventListener('click', () => { storyIndex = (storyIndex + stories.length - 1) % stories.length; renderStory(); });
  document.querySelector('.menu-button')?.addEventListener('click', () => document.getElementById('mobileNav')?.classList.toggle('open')); document.querySelectorAll('.mobile-nav a').forEach(link => link.addEventListener('click', () => document.getElementById('mobileNav')?.classList.remove('open')));
  const briefForm = document.getElementById('briefForm');
  if (briefForm && !briefForm.querySelector('[name="service"]')) { const serviceLabel = document.createElement('label'); serviceLabel.textContent = 'What would you like RK to handle?'; serviceLabel.innerHTML += '<select name="service"><option value="Full event organisation">Full event organisation</option><option value="Bridal & groom entries">Bridal & groom entries</option><option value="Decoration & sound setup">Decoration & sound setup</option><option value="International artist shows">International artist shows</option><option value="Event planning & coordination">Event planning & coordination</option><option value="Choreography & rehearsal">Choreography & rehearsal</option></select>'; briefForm.insertBefore(serviceLabel, briefForm.querySelector('label:last-of-type')); if (state.service) serviceLabel.querySelector('select').value = state.service; }
  briefForm?.addEventListener('submit', event => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); saveState({ brief: data, eventType: data.type, service: data.service }); event.currentTarget.style.display = 'none'; document.getElementById('formSuccess').classList.add('show'); refreshIcons(); });
  document.querySelector('#loginModal .primary-button')?.addEventListener('click', () => { closeModals(); window.location.href = 'auth.html'; }); document.querySelectorAll('.footer-social a[href="#"]').forEach(link => link.addEventListener('click', event => { event.preventDefault(); showToast('RK social links are coming soon'); }));
  const sections = [...document.querySelectorAll('main section[id]')]; const navLinks = [...document.querySelectorAll('.main-nav a')]; const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) navLinks.forEach(link => link.classList.toggle('active', link.getAttribute('href') === `#${entry.target.id}` || entry.target.id === 'brief' && link.getAttribute('href') === '#top')); }), { rootMargin: '-35% 0px -55%' }); sections.forEach(section => observer.observe(section));
});
